server:
  port: 80

#设置应用id
spring:
  application:
    name: cloud-consumer-order

#注册eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间 单位毫秒
  ReadTimeout: 5000 # == 5秒钟
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#  开启日志的Feign客户端
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.xsx.springcloud.service.PaymentOpenFeignService: debug
