server:
  port: 2002

spring:
  application:
    name: seata-storage-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        #service.vgroupMapping. my_test_tx_group
        tx-service-group:
          my_test_tx_group: default
    nacos:
      discovery:
        server-addr: 192.168.43.197:1111
        group: SEATA_GROUP
        cluster-name: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.197:3306/seata_storage?serverTimezone=UTC
    username: root
    password:

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  #扫描类路径下的mapper映射文件
  mapperLocations: classpath:mapper/*.xml



