server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.197:1111 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
