server:
  port: 8001

spring:
  #声明应用名-唯一(为了注册必须声明)
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC
    username: root
    password: admin

#声明mbatis mapper配置文件位置;为实体类定义别名
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.xsx.springcloud.entities    # 所有Entity别名类所在包

#注册eureka地址
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 集群版
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
#      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001
    #每次发送心跳的间隔 默认值为 30秒
#    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限 ,单位为秒(默认是90秒),超时剔除服务
#    lease-expiration-duration-in-seconds: 2
