server:
  port: 8002

spring:
  #声明应用名-唯一(为了注册必须声明)
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC
    username: root
    password: admin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于 0 到 1 之间，1 则表示全部采集
      probability: 1

#声明mbatis mapper配置文件位置;为实体类定义别名
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.xsx.springcloud.entities    # 所有Entity别名类所在包

#注册eureka地址
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 集群版
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8002
